/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class AhoCorasick {
  constructor(patterns: Array<string>, options?: Options | undefined | null)
  get patternCount(): number
  toPrepared(): Buffer
  isMatch(haystack: string): boolean
  _findIterPacked(haystack: string): Uint32Array
  _findOverlappingIterPacked(haystack: string): Uint32Array
  replaceAll(haystack: string, replacements: Array<string>): string
  findIterBuf(haystack: Buffer): Array<Match>
  _findIterPackedBuf(haystack: Buffer): Uint32Array
  isMatchBuf(haystack: Buffer): boolean
  findInChunk(chunk: Buffer): Array<Match>
}

export declare class StreamMatcher {
  constructor(patterns: Array<string>, options?: Options | undefined | null)
  write(chunk: Buffer): Array<Match>
  flush(): Array<Match>
  reset(): void
}

export declare function ahoCorasickFromPrepared(bytes: Buffer): AhoCorasick

export interface Match {
  pattern: number
  start: number
  end: number
}

export declare const enum MatchKind {
  LeftmostFirst = 'leftmost-first',
  LeftmostLongest = 'leftmost-longest'
}

export interface Options {
  matchKind?: MatchKind
  caseInsensitive?: boolean
  dfa?: boolean
  wholeWords?: boolean
  unicodeBoundaries?: boolean
}

export declare function prepareAhoCorasick(patterns: Array<string>, options?: Options | undefined | null): Buffer
