/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Aho-Corasick automaton for multi-pattern string
 * searching.
 */
export declare class AhoCorasick {
  /**
   * Build an Aho-Corasick automaton from the given
   * patterns.
   */
  constructor(patterns: Array<string>, options?: Options | undefined | null)
  /** Number of patterns in the automaton. */
  get patternCount(): number
  /** Returns `true` if any pattern matches. */
  isMatch(haystack: string): boolean
  /** Find all non-overlapping matches. */
  findIter(haystack: string): Array<Match>
  /**
   * Find all overlapping matches.
   *
   * Reports every match at every position, including
   * those that overlap with each other.
   */
  findOverlappingIter(haystack: string): Array<Match>
  /**
   * Replace all non-overlapping matches.
   *
   * `replacements[i]` replaces pattern `i`.
   */
  replaceAll(haystack: string, replacements: Array<string>): string
  /**
   * Find matches in a `Buffer` / `Uint8Array`.
   * Returns **byte offsets**.
   */
  findIterBuf(haystack: Buffer): Array<Match>
  /** Check whether any pattern matches in a `Buffer`. */
  isMatchBuf(haystack: Buffer): boolean
  /**
   * Find matches in a single chunk. Byte offsets are
   * relative to the chunk start.
   */
  findInChunk(chunk: Buffer): Array<Match>
}

/**
 * Streaming matcher that handles chunk boundaries.
 *
 * Feed chunks via `write()` and collect matches.
 * Internally buffers the overlap region between
 * chunks so cross-boundary matches are found.
 */
export declare class StreamMatcher {
  /** Create a streaming matcher. */
  constructor(patterns: Array<string>, options?: Options | undefined | null)
  /**
   * Feed a chunk and return matches with global byte
   * offsets.
   */
  write(chunk: Buffer): Array<Match>
  /** Flush remaining state. Call after the last chunk. */
  flush(): Array<Match>
  /** Reset for reuse with new input. */
  reset(): void
}

/** A single match returned by the search methods. */
export interface Match {
  /** Index into the patterns array. */
  pattern: number
  /** Start **character** offset in the haystack. */
  start: number
  /** End **character** offset (exclusive). */
  end: number
}

/** Which match semantics to use. */
export declare const enum MatchKind {
  /**
   * Report the first pattern that matches at each
   * position (order = insertion order).
   */
  LeftmostFirst = 'leftmost-first',
  /**
   * Report the longest pattern that matches at each
   * position.
   */
  LeftmostLongest = 'leftmost-longest'
}

/** Options for constructing an `AhoCorasick` automaton. */
export interface Options {
  /** Match semantics. Default: `"leftmost-first"`. */
  matchKind?: MatchKind
  /** Case-insensitive matching. Default: `false`. */
  caseInsensitive?: boolean
  /** Force DFA mode. Default: `false` (auto NFA). */
  dfa?: boolean
}
